# Lab 11

### Task 1

```bash
kubectl create secret generic my-secret \
  --from-literal=MY_USER=m \
  --from-literal=MY_PASS=myHPpass
```
- Output:
```bash
/my-secret created
```

### Find secret

```bash
kubectl get secrets my-secret -o yaml
```
- Output:
```bash
apiVersion: v1
data:
  MY_PASS: bXlIUHBhc3M=
  MY_USER: bQ==
kind: Secret
metadata:
  creationTimestamp: "2025-03-09T18:58:42Z"
  name: my-secret
  namespace: default
  resourceVersion: "489"
  uid: 16a34d97-179e-4270-ba47-6c23409d5a59
type: Opaque
```

### Decode secrets

```bash
kubectl get secret my-secret -o jsonpath='{.data.MY_USER}' | base64 --decode
```
- Output:
```bash
m
```

```bash
kubectl get secret my-secret -o jsonpath='{.data.MY_PASS}' | base64 --decode
```
- Output:
```bash
myHPpass
```
### Helm secrets

### Output of kubectl get po

```bash
NAME                      READY   STATUS             RESTARTS      AGE
my-app-58df666ff5-pg5cw   0/1     CrashLoopBackOff   5 (23s ago)   3m21s
```

I got an error with starting container

Output of kubectl describe:
```bash
Name:             my-app-58df666ff5-pg5cw
Namespace:        default
Priority:         0
Service Account:  my-app
Node:             minikube/192.168.49.2
Start Time:       Sat, 15 Mar 2025 21:15:34 +0300
Labels:           app.kubernetes.io/instance=my-app
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=my-app
                  app.kubernetes.io/version=1.16.0
                  helm.sh/chart=my-app-0.1.0
                  pod-template-hash=58df666ff5
Annotations:      <none>
Status:           Running
IP:               10.244.0.24
IPs:
  IP:           10.244.0.24
Controlled By:  ReplicaSet/my-app-58df666ff5
Containers:
  my-app:
    Container ID:   docker://9160fa80c2509efc9d98365717a0b38f8dd9b312100869d5c70274ad5604cb5d
    Image:          app_python:latest
    Image ID:       docker-pullable://mattway224/app_python@sha256:a1f1fb0d5f5eb51de2cf42ddbf2727d47dacef4db62c3aa564de4b258125f890
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 15 Mar 2025 21:16:29 +0300
      Finished:     Sat, 15 Mar 2025 21:16:30 +0300
    Ready:          False
    Restart Count:  3
    Liveness:       http-get http://:8080/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/ delay=10s timeout=1s period=5s #success=1 #failure=3
    Environment:
      MY_USER:  <set to the key 'MY_USER' in secret 'my-secret'>  Optional: false
      MY_PASS:  <set to the key 'MY_PASS' in secret 'my-secret'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-s4jlr (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  kube-api-access-s4jlr:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  64s                default-scheduler  Successfully assigned default/my-app-58df666ff5-pg5cw to minikube
  Normal   Pulled     9s (x4 over 63s)   kubelet            Container image "app_python:latest" already present on machine
  Normal   Created    9s (x4 over 63s)   kubelet            Created container: my-app
  Normal   Started    9s (x4 over 63s)   kubelet            Started container my-app
  Warning  BackOff    3s (x11 over 61s)  kubelet            Back-off restarting failed container my-app in pod my-app-58df666ff5-pg5cw_default(5b43f6ff-c2f0-479a-91ac-f4fe2e1cc49b)
```

actually, i don't know why it is did not run successfully

Output of kubectl logs my-app-58df666ff5-pg5cw

```bash
Traceback (most recent call last):
  File "/app/run.py", line 4, in <module>
    from prometheus_client import Counter, generate_latest
ModuleNotFoundError: No module named 'prometheus_client'
```
This is strange, because docker container successfully built, pushed and ran.

Anyway, the output of:
```bash
kubectl describe po my-app | grep MY_PASS
```

```bash
MY_PASS:  <set to the key 'MY_PASS' in secret 'my-secret'>  Optional: false
```
i cannot use exec function 'cause container from pod did not started


## Task 2

### Output of kubectl describe pod vault-0

```bash
Name:             vault-0
Namespace:        default
Priority:         0
Service Account:  vault
Node:             minikube/192.168.49.2
Start Time:       Sat, 15 Mar 2025 21:25:38 +0300
Labels:           app.kubernetes.io/instance=vault
                  app.kubernetes.io/name=vault
                  apps.kubernetes.io/pod-index=0
                  component=server
                  controller-revision-hash=vault-b75cdb86b
                  helm.sh/chart=vault-0.29.1
                  statefulset.kubernetes.io/pod-name=vault-0
Annotations:      <none>
Status:           Running
IP:               10.244.0.27
IPs:
  IP:           10.244.0.27
Controlled By:  StatefulSet/vault
Containers:
  vault:
    Container ID:  docker://ac9d90704d1452c361ba3fa5dd1b1f762eeabcc08561fdd86dada8ea0f26f3b5
    Image:         hashicorp/vault:1.18.1
    Image ID:      docker-pullable://hashicorp/vault@sha256:3580fa352195aa7e76449cb8fadeef6d2f90a454c38982d30cf094e9013be786
    Ports:         8200/TCP, 8201/TCP, 8202/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/sh
      -ec
    Args:
      /usr/local/bin/docker-entrypoint.sh vault server -dev 
      
    State:          Running
      Started:      Sat, 15 Mar 2025 21:26:58 +0300
    Ready:          True
    Restart Count:  0
    Readiness:      exec [/bin/sh -ec vault status -tls-skip-verify] delay=5s timeout=3s period=5s #success=1 #failure=2
    Environment:
      HOST_IP:                    (v1:status.hostIP)
      POD_IP:                     (v1:status.podIP)
      VAULT_K8S_POD_NAME:        vault-0 (v1:metadata.name)
      VAULT_K8S_NAMESPACE:       default (v1:metadata.namespace)
      VAULT_ADDR:                http://127.0.0.1:8200
      VAULT_API_ADDR:            http://$(POD_IP):8200
      SKIP_CHOWN:                true
      SKIP_SETCAP:               true
      HOSTNAME:                  vault-0 (v1:metadata.name)
      VAULT_CLUSTER_ADDR:        https://$(HOSTNAME).vault-internal:8201
      HOME:                      /home/vault
      VAULT_DEV_ROOT_TOKEN_ID:   root
      VAULT_DEV_LISTEN_ADDRESS:  [::]:8200
    Mounts:
      /home/vault from home (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9sftj (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
Volumes:
  home:
    Type:       EmptyDir (a temporary directory that shares a pods lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-9sftj:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  5m6s   default-scheduler  Successfully assigned default/vault-0 to minikube
  Normal  Pulling    5m5s   kubelet            Pulling image "hashicorp/vault:1.18.1"
  Normal  Pulled     3m48s  kubelet            Successfully pulled image "hashicorp/vault:1.18.1" in 39.382s (1m17.415s including waiting). Image size: 466386752 bytes.
  Normal  Created    3m46s  kubelet            Created container: vault
  Normal  Started    3m46s  kubelet            Started container vault
```

### Output of 
```bash
kubectl exec -it vault-0 -- vault kv put secret/my-app MY_PASS=m_hp_pass
```

```bash
=== Secret Path ===
secret/data/my-app

======= Metadata =======
Key                Value
---                -----
created_time       2025-03-15T18:30:48.799009381Z
custom_metadata    <nil>
deletion_time      n/a
destroyed          false
version            2
```