## Internet failure

I have had a very problematic issue with the internet close to the deadline, as of writing this I managed to fix it, but now I am past the deadline, I hope you will forgive me.

My original quick fixes were of bad quality, partially because the issue was not in the configs but in docker hub connection, so that was changed, too.


```bash
minikube kubectl -- get po
```
```bash
NAME                          READY   STATUS    RESTARTS   AGE
python-app-6f79584998-d7lhq   1/1     Running   0          25s
```

```bash
minikube kubectl get configmaps
```
```bash
NAME               DATA   AGE
config             2      113s
kube-root-ca.crt   1      33m
```

```bash
minikube kubectl -- describe configmaps config
```
```bash
Name:         config
Namespace:    default
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: python-app
              meta.helm.sh/release-namespace: default

Data
====
name:
----
Ivan

surname:
----
Lishchenko


BinaryData
====

Events:  <none>
```
This is what I originaly did and see, but now I actually got to show it.

```bash
minikube kubectl -- exec -it python-app-6f79584998-d7lhq --container python-app -- /bin/sh
```
```bash
/ $ ls
bin     dev     home    media   opt     root    sbin    sys     usr
config  etc     lib     mnt     proc    run     srv     tmp     var
/ $ cd tmp
/tmp $ ls
visits.txt
/tmp $ cat visits.txt 
62
/tmp $ cd ..
/ $ ls
bin     dev     home    media   opt     root    sbin    sys     usr
config  etc     lib     mnt     proc    run     srv     tmp     var
/ $ cd config
/config $ ls
name     surname
/config $ cat name
Ivan 
/config $ cat surname
Lishchenko
```

This proves that the information is readily available.

```bash
minikube kubectl -- describe po
```
```bash
Name:             python-app-6f79584998-d7lhq
Namespace:        default
Priority:         0
Service Account:  python-app
Node:             minikube/192.168.49.2
Start Time:       Sun, 09 Mar 2025 21:17:45 +0000
Labels:           app.kubernetes.io/instance=python-app
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=python-app
                  app.kubernetes.io/version=1.16.0
                  helm.sh/chart=python-app-0.1.0
                  pod-template-hash=6f79584998
Annotations:      vault.hashicorp.com/agent-inject: true
                  vault.hashicorp.com/agent-inject-secret-database-config.txt: internal/data/database/config
                  vault.hashicorp.com/agent-inject-status: update
                  vault.hashicorp.com/agent-inject-template-database-config.txt:
                    {{- with secret "internal/data/database/config" -}}
                    postgresql://{{ .Data.data.username }}:{{ .Data.data.password }}@postgres:5432/wizard
                    {{- end -}}
                  vault.hashicorp.com/role: python-app
Status:           Running
IP:               10.244.0.20
IPs:
  IP:           10.244.0.20
Controlled By:  ReplicaSet/python-app-6f79584998
Containers:
  python-app:
    Container ID:   docker://6e9ae299b6bfede36e878617a4496f06f4f786c15bff7b1a7c4f777043b64fb1
    Image:          registry.hub.docker.com/magel0n/moscowtimeimagepython:latest
    Image ID:       docker-pullable://registry.hub.docker.com/magel0n/moscowtimeimagepython@sha256:07359c29dc6fa1a4099b4d7fb6ba587eb704bd9022e60bc2d7b60fb4380eb448
    Port:           5000/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Sun, 09 Mar 2025 21:17:51 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  128Mi
    Requests:
      cpu:      1
      memory:   128Mi
    Liveness:   http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      config  ConfigMap  Optional: false
    Environment:
      MY_PASSWORD:  <set to the key 'password' in secret 'credentials'>  Optional: false
    Mounts:
      /config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-brqdz (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      config
    Optional:  false
  kube-api-access-brqdz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  15m   default-scheduler  Successfully assigned default/python-app-6f79584998-d7lhq to minikube
  Normal  Pulling    15m   kubelet            Pulling image "registry.hub.docker.com/magel0n/moscowtimeimagepython:latest"
  Normal  Pulled     15m   kubelet            Successfully pulled image "registry.hub.docker.com/magel0n/moscowtimeimagepython:latest" in 2.341s (2.341s including waiting). Image size: 58237857 bytes.
  Normal  Created    15m   kubelet            Created container: python-app
  Normal  Started    15m   kubelet            Started container python-app
```