## Internet failure

I have tried to add the elements, it even worked, but then I decided to update the image as I have changed it due to task 1, which resulted in failure at this task.

The reason is the shady internet connection of innopolis, you can see it in the logs: the TLS handshake failed multiple times.

I did see the correct information in the terminal, but I deleted that to repeat the process with the new version of the image. Then I tried many different fixes, but there is not enough time and so I will be providiing this here and now.

```bash
minikube kubectl -- describe pods
```
```
Name:             python-app-cd474488-n6gsz
Namespace:        default
Priority:         0
Service Account:  python-app
Node:             minikube/192.168.49.2
Start Time:       Sun, 09 Mar 2025 20:53:16 +0000
Labels:           app.kubernetes.io/instance=python-app
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=python-app
                  app.kubernetes.io/version=1.16.0
                  helm.sh/chart=python-app-0.1.0
                  pod-template-hash=cd474488
Annotations:      vault.hashicorp.com/agent-inject: true
                  vault.hashicorp.com/agent-inject-secret-database-config.txt: internal/data/database/config
                  vault.hashicorp.com/agent-inject-status: update
                  vault.hashicorp.com/agent-inject-template-database-config.txt:
                    {{- with secret "internal/data/database/config" -}}
                    postgresql://{{ .Data.data.username }}:{{ .Data.data.password }}@postgres:5432/wizard
                    {{- end -}}
                  vault.hashicorp.com/role: python-app
Status:           Pending
IP:               10.244.0.11
IPs:
  IP:           10.244.0.11
Controlled By:  ReplicaSet/python-app-cd474488
Containers:
  python-app:
    Container ID:   
    Image:          registry.hub.docker.com/magel0n/moscowtimeimagepython:latest
    Image ID:       
    Port:           5000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  128Mi
    Requests:
      cpu:      1
      memory:   128Mi
    Liveness:   http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      config  ConfigMap  Optional: false
    Environment:
      MY_PASSWORD:  <set to the key 'password' in secret 'credentials'>  Optional: false
    Mounts:
      /config from config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dckqt (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      app-config
    Optional:  false
  kube-api-access-dckqt:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  2m4s                default-scheduler  Successfully assigned default/python-app-cd474488-n6gsz to minikube
  Normal   Pulled     101s                kubelet            Successfully pulled image "registry.hub.docker.com/magel0n/moscowtimeimagepython:latest" in 21.067s (21.068s including waiting). Image size: 58237857 bytes.
  Normal   Pulled     97s                 kubelet            Successfully pulled image "registry.hub.docker.com/magel0n/moscowtimeimagepython:latest" in 1.88s (3.022s including waiting). Image size: 58237857 bytes.
  Normal   Pulled     70s                 kubelet            Successfully pulled image "registry.hub.docker.com/magel0n/moscowtimeimagepython:latest" in 11.794s (11.794s including waiting). Image size: 58237857 bytes.
  Warning  Failed     45s                 kubelet            Failed to pull image "registry.hub.docker.com/magel0n/moscowtimeimagepython:latest": Error response from daemon: Get "https://registry.hub.docker.com/v2/": net/http: TLS handshake timeout
  Warning  Failed     30s (x4 over 101s)  kubelet            Error: configmap "config" not found
  Normal   Pulled     30s                 kubelet            Successfully pulled image "registry.hub.docker.com/magel0n/moscowtimeimagepython:latest" in 2.261s (2.261s including waiting). Image size: 58237857 bytes.
  Normal   Pulling    16s (x6 over 2m2s)  kubelet            Pulling image "registry.hub.docker.com/magel0n/moscowtimeimagepython:latest"
  Warning  Failed     1s (x2 over 45s)    kubelet            Error: ErrImagePull
  Warning  Failed     1s                  kubelet            Failed to pull image "registry.hub.docker.com/magel0n/moscowtimeimagepython:latest": Error response from daemon: Head "https://registry.hub.docker.com/v2/magel0n/moscowtimeimagepython/manifests/latest": net/http: TLS handshake timeout
```

Configs did show up there and I saw Lishchenko Ivan, as in the .json, but due to wifi reasons it does not work, please, I hope I submit this in time.

